// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Bye(arg1) {
  return window['go']['main']['App']['Bye'](arg1);
}

export function CurrentCtx() {
  return window['go']['main']['App']['CurrentCtx']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function KubeConfig() {
  return window['go']['main']['App']['KubeConfig']();
}

export function KubeSwitch(arg1) {
  return window['go']['main']['App']['KubeSwitch'](arg1);
}
