// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Bye(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function KubeConfig():Promise<Array<string>>;

export function KubeSwitch(arg1:string):Promise<string>;
